src/Entity/Links.php
<?php

namespace App\Entity;

use App\Repository\LinksRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=LinksRepository::class)
 * @Vich\Uploadable
 */
class Links
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $hyperlink;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $position;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *
     * @var int
     */
    private $position_order;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $alt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface
     */
    private $updated_at;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="images", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     *
     * @var bool
     */
    private $is_active;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     *
     * @var bool
     */
    private $is_video;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTimeInterface
     */
    private $uploaded_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getHyperlink(): ?string
    {
        return $this->hyperlink;
    }

    public function setHyperlink(string $hyperlink): self
    {
        $this->hyperlink = $hyperlink;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getPositionOrder(): ?int
    {
        return $this->position_order;
    }

    public function setPositionOrder(int $position_order): self
    {
        $this->position_order = $position_order;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if (null !== $imageFile) {
            $this->updated_at = new \DateTimeImmutable();
        }
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getIsVideo(): ?bool
    {
        return $this->is_video;
    }

    public function setIsVideo(?bool $is_video): self
    {
        $this->is_video = $is_video;

        return $this;
    }

    public function getUploadedAt(): ?\DateTimeInterface
    {
        return $this->uploaded_at;
    }

    public function setUploadedAt(?\DateTimeInterface $uploaded_at): self
    {
        $this->uploaded_at = $uploaded_at;

        return $this;
    }
}

src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=PostsRepository::class)
 */
class Posts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $metaTitle;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $metaDescription;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $content;

    /**
     * @ORM\Column(type="json", nullable=true)
     *
     * @var array<int, string>
     */
    private $keywords = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     *
     * @var array<int, string>
     */
    private $metaKeywords = [];

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="posts", cascade={"persist"})
     *
     * @var Collection|Images[]
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="post")
     *
     * @var Collection|Comments[]
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $is_past_concert;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=255, unique=true, nullable=true)
     *
     * @var string
     */
    private $slug;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->metaTitle;
    }

    public function setMetaTitle(string $metaTitle): self
    {
        $this->metaTitle = $metaTitle;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->metaDescription;
    }

    public function setMetaDescription(string $metaDescription): self
    {
        $this->metaDescription = $metaDescription;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Undocumented function.
     *
     * @return array<int, string>|null
     */
    public function getKeywords(): ?array
    {
        return $this->keywords;
    }

    /**
     * Undocumented function.
     *
     * @param array<int, string>|null $keywords
     */
    public function setKeywords(?array $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    /**
     * Undocumented function.
     *
     * @return array<int, string>|null
     */
    public function getMetaKeywords(): ?array
    {
        return $this->metaKeywords;
    }

    /**
     * Undocumented function.
     *
     * @param array<int, string>|null $metaKeywords
     */
    public function setMetaKeywords(?array $metaKeywords): self
    {
        $this->metaKeywords = $metaKeywords;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setPosts($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getPosts() === $this) {
                $image->setPosts(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsPastConcert(): ?bool
    {
        return $this->is_past_concert;
    }

    public function setIsPastConcert(bool $is_past_concert): self
    {
        $this->is_past_concert = $is_past_concert;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Entity/Shows.php
<?php

namespace App\Entity;

use App\Repository\ShowsRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ShowsRepository::class)
 * @Vich\Uploadable
 */
class Shows
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $location;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $metaDescription;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $metaTitle;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface
     */
    private $expected_at;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $description;

    /**
     * @ORM\Column(type="json", nullable=true)
     *
     * @var array<int, string>
     */
    private $metaKeywords = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     *
     * @var array<int, string>
     */
    private $keywords = [];

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=255, unique=true)
     *
     * @var string
     */
    private $slug;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="images", fileNameProperty="image")
     */
    private $imageFile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->metaDescription;
    }

    public function setMetaDescription(string $metaDescription): self
    {
        $this->metaDescription = $metaDescription;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->metaTitle;
    }

    public function setMetaTitle(string $metaTitle): self
    {
        $this->metaTitle = $metaTitle;

        return $this;
    }

    public function getExpectedAt(): ?\DateTimeInterface
    {
        return $this->expected_at;
    }

    public function setExpectedAt(\DateTimeInterface $expected_at): self
    {
        $this->expected_at = $expected_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Undocumented function.
     *
     * @return array<int, string>|null
     */
    public function getMetaKeywords(): ?array
    {
        return $this->metaKeywords;
    }

    /**
     * Undocumented function.
     *
     * @param array<int, string>|null $metaKeywords
     */
    public function setMetaKeywords(?array $metaKeywords): self
    {
        $this->metaKeywords = $metaKeywords;

        return $this;
    }

    /**
     * Undocumented function.
     *
     * @return array<int, string>|null
     */
    public function getKeywords(): ?array
    {
        return $this->keywords;
    }

    /**
     * Undocumented function.
     *
     * @param array<int, string>|null $keywords
     */
    public function setKeywords(?array $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if (null !== $imageFile) {
            $this->updated_at = new \DateTimeImmutable();
        }
    }
}

templates/home/concerts.html.twig
{% extends 'base.html.twig' %}

{% set currentUrl = url(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) %}

{% block head %}
{# Instagram #}
<meta property="og:title" content="{{ post.metaTitle ?? '' }}">
<meta property="og:description" content="{{ post.metaDescription ?? '' }}">
<meta property="og:url" content="{{ currentUrl }}">
<meta property="og:type" content="website">
{# Fin Instagram #}

<meta name="description" content="{{ post.metaDescription ?? '' }}">


<script type="application/ld+json">
[
    {% for show in shows|sort((a, b) => b.expectedAt <=> a.expectedAt) %}
        { 
            "@context": "http://schema.org",
            "@type": "Event",
            "name": "{{ show.metaTitle }}",
            "description": "{{ show.metaDescription }}",
            "url":"{{ currentUrl }}",
            "startDate":"{{ show.expectedAt ? show.expectedAt|date('Y-m-d H:i:s') : '' }}",
            "endDate":"{{ show.expectedAt ? show.expectedAt|date('Y-m-d H:i:s') : '' }}",
            "image": "{{ asset('images/' ~ show.image )|imagine_filter('min300') }}",
            "performer": "Tunkal",
            "organizer": "",
            "location": {
                "@type": "Place",
                "name": "{{ show.location }}",
                "description": "",
                "url": false,
                "address": {
                    "@type": "PostalAddress",
                    "streetAddress": ""
                },
                "telephone": "",
                "sameAs": ""
            }
        }{{ loop.last ? '' : ',' }}
    {% endfor %}
]
</script>




{% endblock %}

{% block title %}{{ post.metaTitle ?? '' }}{% endblock %}

{% block body %}

    <section class="concerts">

        <h2>{{ post.metaTitle ?? '' }}</h2>

    
        {% for show in shows|sort((a, b) => b.expectedAt <=> a.expectedAt) %}
            <article>
                <h3>{{ show.title }}</h3>
                <div>{{ show.description|raw }}</div>

                <div>
                    <p>Quand ? {{ show.expectedAt ? show.expectedAt|date('d-m-Y H:i:s') : '' }}</p>
                    <p>Où ? {{ show.location }}</p>
                </div>

                {# Illustration article #}
                {% if show.image is defined %}
                    <img src="{{ asset('images/' ~ show.image )|imagine_filter('min300') }}" alt="{{ show.metaTitle ?? '' }}">
                {% endif %}
                {# Fin Illustration article #}

                {# <p class="keywords">
                    {% for keyword in show.keywords %}
                        # <strong>{{ keyword }}</strong>
                    {% endfor %}
                </p> #}

                {# <a href="{{ path('show', {'slug': show.slug}) }}" title="Aller à l'article {{ post.title }}">Lire l'article</a> #}
            </article>
        {% endfor %}
    </section>

{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% set currentUrl = url(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) %}

{% block head %}
{# Instagram #}
<meta property="og:title" content="{{ post.metaTitle ?? '' }}">
<meta property="og:description" content="{{ post.metaDescription ?? '' }}">
<meta property="og:url" content="{{ currentUrl }}">
<meta property="og:type" content="website">
{# Fin Instagram #}

<meta name="description" content="{{ post.metaDescription ?? '' }}">

<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "MusicGroup",
    "name": "Tunkal",
    "description": "{{ post.metaDescription ?? '' }}",
    "logo": {
        "@type": "ImageObject",
        "url": "{{ asset('images/logo.webp') }}"
    },
    "image": {
        "@type": "ImageObject",
        "url": "{{ asset('images/photo.webp') }}"
    },
    "url": "{{ currentUrl }}",
    "genre": [
        "Metal",
        "Death Metal",
        "Thrash Metal"
    ],
    "sameAs": [
    {% for link in links()|filter( link => link.position == 'header' ) %}
        "{{ link.hyperlink }}"{{ loop.last ? '' : ',' }}
    {% endfor %}
    ],
    "foundingLocation": {
        "@type": "Country",
        "name": "France"
    },
    "foundingDate": "2018",
    "track": [
    {% for link in links()|filter( link =>  link.position == 'media' ) %}
    {
        {% if link.isVideo == false %}
        "@type": "MusicRecording",
        "audio": "{{ link.hyperlink }}",
        "name": "{{ link.content }}",
        "url": "{{ link.hyperlink }}"   
        {% else %}
        "@type": "VideoObject",
        "name": "{{ link.title }}",
        "description": "{{ link.content }}",
        "embedUrl": "{{ link.hyperlink }}",
		"thumbnailUrl":"{{ asset('images/' ~ link.image )|imagine_filter('min300') }}",
        "uploadDate":"{{ link.uploadedAt|date("c") }}"
        {% endif %}
    }{{ loop.last ? '' : ',' }}
    {% endfor %}
    ],
    "member": [
        {
        "@type": "OrganizationRole",
        "member": {
            "@type": "Person",
            "name": "Tunkal"
        },
        "startDate": "2018",
        "roleName": "guitar"
        }
    ]
}
</script>
{% endblock %}

{% block title %}{{ post.metaTitle ?? '' }}{% endblock %}

{% block body %}

    <article class="index">
        <h2>{{ post.title ?? '' }}</h2>
        <div>
            <div>{{ post.content|raw }}</div>
            {# Illustration article #}
            {% for image in post.images %}
                <img class="hover-shadow" data-currentslide="{{ loop.index0 }}"
                src="{{  asset('images/' ~ image.name )|imagine_filter('min300') }}" alt="{{ post.metaTitle ?? '' }}" data-image-path="{{ asset('images/' ~ image.name ) }}" >
            {% endfor %}
            {# Fin Illustration article #}        
        </div>

        <!-- The Modal -->
        <div id="myModal" class="modal">
            <span class="close">&times;</span>
            <div class="mySlides">
                <img src="{{ post.images[0].name ? asset('images/' ~ post.images[0].name )|imagine_filter('min300') : '' }}" alt="{{ post.metaTitle ?? '' }}">
            </div>
            <!-- Next/previous controls -->
            {% if post.images|length > 1 %}
                <span class="prev" data-plus="-1">&#10094;</span>
                <span class="next" data-plus="1">&#10095;</span>            
            {% endif %}

        </div> 

        {# <p class="keywords">
            {% for keyword in post.keywords %}
                #<strong>{{ keyword }}</strong>
            {% endfor %}
        </p> #}
    </article>

    <section class="tracks">
        <h2>Listen Tunkal music on Youtube : </h2>
        <ul>
            {% for link in mediaLinks|filter( link => link.isVideo == true ) %}
            <li>
                <a class="player" href="#" title="watch {{ link.title }} on Youtube" id="player{{ loop.index0 }}" data-videoid="{{ link.hyperlink }}">
                    <img class="video" src="{{ asset('images/' ~ link.image )|imagine_filter('min300') }}" alt="Thumbnail of {{ link.title }} video">
                    <img src="{{ asset('images/YouTube_23392.ico') }}" alt="logo Youtube">
                </a>
            </li>
            {% endfor %}	
        </ul>
        <ul>
            {% for link in mediaLinks|filter( link => link.isVideo == false ) %}
            <li>
                <a href="{{ link.hyperlink }}" title="{{ link.title }}" target="_blank"><img src="{{ asset('images/YouTube_23392.ico') }}" alt="logo Youtube">&nbsp;{{ link.content }}</a> 
            </li>
            {% endfor %}	
        </ul>
        <div>
            <a href="{{ copyrightLink.hyperlink }}" title="{{ copyrightLink.title }}" target="_blank">{{ copyrightLink.content|raw }}</a>
        </div>
    </section>

{% endblock %}

{% block javascripts %}
	<script src="https://s.ytimg.com/yts/jsbin/www-widgetapi-vfl7r2f24/www-widgetapi.js" async defer></script>
    {{ encore_entry_script_tags('loadvideo') }}
{% endblock %}

templates/home/news.html.twig
{% extends 'base.html.twig' %}

{% set currentUrl = url(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) %}

{% block head %}
{# Instagram #}
<meta property="og:title" content="{{ post.metaTitle ?? '' }}">
<meta property="og:description" content="{{ post.metaDescription ?? '' }}">
<meta property="og:url" content="{{ currentUrl }}">
<meta property="og:type" content="website">
{# Fin Instagram #}

<meta name="description" content="{{ post.metaDescription ?? '' }}">
{% endblock %}

{% block title %}{{ post.metaTitle ?? '' }}{% endblock %}

{% block body %}

<section class="news">

<h2>{{ post.metaTitle }}</h2>

{% for post in posts|sort((a, b) => b.createdAt <=> a.createdAt) %}
    <article>
        <h3>{{ post.title }}</h3>
        <p class="createdAt">Le <time datetime="{{ post.createdAt|date('Y-m-d') }}">{{ post.createdAt|date('d-m-Y') }}</time></p>
        <div>
            <p>{{ post.metaDescription }}</p>
            {# Illustration article #}
            {% if post.images|length > 0 %}
                <img src="{{ asset('images/' ~ post.images[0].name )|imagine_filter('min300') }}" alt="{{ post.metaTitle ?? '' }}">
            {% endif %}
            {# Fin Illustration article #}
        </div>

        {# <p class="keywords">
            {% for keyword in post.keywords %}
                #<strong>{{ keyword }}</strong>
            {% endfor %}
        </p>   #}
        
        {% if post.isPastConcert %}
            <a href="{{ path('pastConcert', {'slug': post.slug}) }}" title="Aller à l'article {{ post.title }}">Lire</a>   
        {% else %}
            <a href="{{ path('post', {'slug': post.slug}) }}" title="Aller à l'article {{ post.title }}">Lire</a>
        {% endif %}
    </article>

{% endfor %}

</section>

{% endblock %}

templates/home/post.html.twig
{% extends 'base.html.twig' %}

{% set currentUrl = url(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) %}

{% block head %}
{# Instagram #}
<meta property="og:title" content="{{ post.metaTitle ?? '' }}">
<meta property="og:description" content="{{ post.metaDescription ?? '' }}">
<meta property="og:url" content="{{ currentUrl }}">
<meta property="og:type" content="website">
{# Fin Instagram #}

<meta name="description" content="{{ post.metaDescription ?? '' }}">
{% endblock %}

{% block title %}{{ post.metaTitle ?? '' }}{% endblock %}

{% block body %}

    {% for message in app.flashes('success') %}
        <div class="success">{{ message }}</div>
    {% endfor %}
    <div id="comment_sent"></div>

    <article class="post">
        <h2>{{ post.title ?? '' }}</h2>
        <p class="createdAt">Le <time datetime="{{ post.createdAt|date('Y-m-d') }}">{{ post.createdAt|date('d-m-Y') }}</time></p>
        <div class="postcontent">{{ post.content|raw }}</div>

        {# Illustration article #}
            {% for image in post.images %}
                <img class="hover-shadow" data-currentslide="{{ loop.index0 }}"
                src="{{ asset('images/' ~ image.name )|imagine_filter('min150') }}" alt="{{ post.metaTitle ?? '' }}" data-image-path="{{ asset('images/' ~ image.name ) }}" >
            {% endfor %}
        {# Fin Illustration article #}

        <!-- The Modal/Lightbox -->
        <div id="myModal" class="modal">
            <span class="close">&times;</span>
            <div class="mySlides">
                <img src="{{ post.images[0].name ? asset('images/' ~ post.images[0].name )|imagine_filter('min150') : '' }}" alt="{{ post.metaTitle ?? '' }}">
            </div>
            <!-- Next/previous controls -->
            {% if post.images|length > 1 %}
                <span class="prev" data-plus="-1">&#10094;</span>
                <span class="next" data-plus="1">&#10095;</span>            
            {% endif %}
        </div> 


        {# <p class="keywords">
            {% for keyword in post.keywords %}
                #<strong>{{ keyword }}</strong>
            {% endfor %}
        </p> #}
    </article>

    <section class="comments" data-slug="{{ post.slug }}">
        <h2>Commentaires</h2>
        {% if numbOfCommentsPages == 0 %}
            <p>0 commentaire pour cet article.</p>
        {% else %}
            <div class="comment">
                <p><span class="pseudo"></span>, le <span class="sent_at"></span> : </p>
                <p class="comment_content"></p>
            </div>
            <p id="seeComments" data-numberofpages="{{ numbOfCommentsPages }}">Voir les commentaires <i class="fas fa-caret-down"></i></p>
        {% endif %}
    </section>

    {# Formulaire commentaire #}
    <div>
        <h2>Écrire un commentaire</h2>
        {{ include('comments/_form.html.twig', {'button_label': 'Envoyer'}) }}
    </div>
    {# Fin Formulaire commentaire #}
{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('appComments') }}
{% endblock %}