src/Entity/Shows.php
<?php

namespace App\Entity;

use App\Repository\ShowsRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ShowsRepository::class)
 * @Vich\Uploadable
 */
class Shows
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $location;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $metaDescription;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $metaTitle;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface
     */
    private $expected_at;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $description;

    /**
     * @ORM\Column(type="json", nullable=true)
     *
     * @var array<int, string>
     */
    private $metaKeywords = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     *
     * @var array<int, string>
     */
    private $keywords = [];

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=255, unique=true)
     *
     * @var string
     */
    private $slug;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="images", fileNameProperty="image")
     */
    private $imageFile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->metaDescription;
    }

    public function setMetaDescription(string $metaDescription): self
    {
        $this->metaDescription = $metaDescription;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->metaTitle;
    }

    public function setMetaTitle(string $metaTitle): self
    {
        $this->metaTitle = $metaTitle;

        return $this;
    }

    public function getExpectedAt(): ?\DateTimeInterface
    {
        return $this->expected_at;
    }

    public function setExpectedAt(\DateTimeInterface $expected_at): self
    {
        $this->expected_at = $expected_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Undocumented function.
     *
     * @return array<int, string>|null
     */
    public function getMetaKeywords(): ?array
    {
        return $this->metaKeywords;
    }

    /**
     * Undocumented function.
     *
     * @param array<int, string>|null $metaKeywords
     */
    public function setMetaKeywords(?array $metaKeywords): self
    {
        $this->metaKeywords = $metaKeywords;

        return $this;
    }

    /**
     * Undocumented function.
     *
     * @return array<int, string>|null
     */
    public function getKeywords(): ?array
    {
        return $this->keywords;
    }

    /**
     * Undocumented function.
     *
     * @param array<int, string>|null $keywords
     */
    public function setKeywords(?array $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if (null !== $imageFile) {
            $this->updated_at = new \DateTimeImmutable();
        }
    }
}

src/Form/ShowsType.php
<?php

namespace App\Form;

use App\Entity\Shows;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ShowsType extends AbstractType
{
    /**
     * Undocumented function.
     *
     * @param array<string, mixed> $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'required' => true,
                'label' => 'Titre du concert : ',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir un titre.',
                    ]),
                ],
            ])
            ->add('location', TextType::class, [
                'required' => true,
                'label' => 'Lieu : ',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir un Lieu.',
                    ]),
                ],
            ])
            ->add('metaTitle', TextType::class, [
                'required' => true,
                'label' => 'Titre méta-donnée du concert : ',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir un titre.',
                    ]),
                    new Length([
                        'min' => 50,
                        'minMessage' => 'Le titre doit comporter au minimum {{ limit }} caractères.',
                        'max' => 70,
                        'maxMessage' => 'Le titre doit comporter au maximum {{ limit }} caractères.',
                    ]),
                ],
            ])
            ->add('description', CKEditorType::class, [
                // 'config_name'=> 'main_config',
                'required' => true,
                'label' => 'Description : ',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir la description',
                    ]),
                ],
            ])
            ->add('metaDescription', TextareaType::class, [
                'required' => true,
                'label' => 'Description en méta-données: ',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir une description.',
                    ]),
                    new Length([
                        'min' => 150,
                        'minMessage' => 'La description doit comporter au minimum {{ limit }} caractères.',
                        'max' => 200,
                        'maxMessage' => 'La description doit comporter au maximum {{ limit }} caractères.',
                    ]),
                ],
            ])
            ->add('keywords', TextType::class, [
                'required' => false,
                'label' => 'Ajouter des mots-clés, délimités par des hashtags ("#"), afin de référencer votre publication : ',
                'mapped' => false,
                'data' => (null != $builder->getData()->getKeywords()) ? implode('#', $builder->getData()->getKeywords()) : '',
            ])
            ->add('metaKeywords', TextType::class, [
                'required' => false,
                'label' => 'Ajouter des mots-clés en méta-données, délimités par des hashtags ("#"), afin de référencer votre publication : ',
                'mapped' => false,
                'data' => (null != $builder->getData()->getMetaKeywords()) ? implode('#', $builder->getData()->getMetaKeywords()) : '',
            ])
            ->add('expected_at', DateType::class, [
                'required' => true,
                'label' => 'Date du concert',
                'widget' => 'single_text',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir une date',
                    ]),
                    new DateTime([
                        'message' => 'La date est invalide',
                    ]),
                ],
            ])
            ->add('imageFile', VichImageType::class, [
                'required' => false,
                'label' => 'Image de présentation',
                'download_uri' => false,
                'imagine_pattern' => 'min300',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Choisir un drapeau',
                        'groups' => ['new'],
                    ]),
                    new Image([
                        'maxSize' => '2M',
                        'maxSizeMessage' => 'Votre image dépasse les 2Mo',
                        'mimeTypes' => ['image/webp'],
                        'mimeTypesMessage' => 'Votre image doit être de type webp',
                        'groups' => ['new', 'update'],
                    ]),
                ],
            ])
            ->add('slug', TextType::class, [
                'required' => false,
                'label' => 'titre ("slug") en barre d\'url : ',
                // 'constraints' => [
                //     new NotBlank([
                //         'message' => 'Veuillez saisir un slug.',
                //     ])
                // ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Shows::class,
        ]);
    }
}

src/Controller/ShowsController.php
<?php

namespace App\Controller;

use App\Entity\Shows;
use App\Form\ShowsType;
use App\Repository\ShowsRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ShowsController extends AbstractController
{
    /**
     * @Route("/admin/shows/", name="shows_index", methods={"GET"})
     */
    public function index(ShowsRepository $showsRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $shows = $paginator->paginate(
            $showsRepository->findAll(),
            //Le numero de la page, si aucun numero, on force la page 1
            $request->query->getInt('page', 1),
            //Nombre d'élément par page
            10
        );

        return $this->render('shows/index.html.twig', [
            'shows' => $shows,
        ]);
    }

    /**
     * @Route("/admin/shows/new", name="shows_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $show = new Shows();
        $form = $this->createForm(ShowsType::class, $show, [
            'validation_groups' => ['new'],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //Récupération des mots-clés en tant que chaine de caractères et séparation en array avec un délimiteur ";"
            $keywords = $form->get('keywords')->getData();
            $keywords = explode('#', $keywords);
            $keywords = array_filter($keywords);
            $show->setKeywords($keywords);

            $keywords = $form->get('metaKeywords')->getData();
            $keywords = explode('#', $keywords);
            $keywords = array_filter($keywords);
            $show->setMetaKeywords($keywords);

            $show->setUpdatedAt(new \DateTime('now', new \DateTimeZone('Europe/Paris')));

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($show);
            $entityManager->flush();

            //Envoi d'un message utilisateur
            $this->addFlash('success', 'Nouveau concert créé.');

            return $this->redirectToRoute('shows_index');
        }

        return $this->render('shows/new.html.twig', [
            'show' => $show,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/shows/{id}", name="shows_show", methods={"GET"})
     */
    public function show(Shows $show): Response
    {
        return $this->render('shows/show.html.twig', [
            'show' => $show,
        ]);
    }

    /**
     * @Route("/admin/shows/{id}/edit", name="shows_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Shows $show, Filesystem $filesystem): Response
    {
        $form = $this->createForm(ShowsType::class, $show, [
            'validation_groups' => ['update'],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $show->setUpdatedAt(new \DateTime('now', new \DateTimeZone('Europe/Paris')));
            //Stockage de l'ancien nom de fichier image
            $oldImage = $show->getImage();

            $this->getDoctrine()->getManager()->flush();

            //Stockage du nouveau nom de fichier après persistement en bdd
            $newImage = $show->getImage();
            //Si le nom de fichier a changé
            if ($oldImage != $newImage) {
                $oldImage = '../public/media/cache/miniatures/images/'.$oldImage;
                if ($filesystem->exists($oldImage)) {
                    //Alors on supprime la miniature correspondante
                    $filesystem->remove($oldImage);
                }
            }
            //Envoi d'un message utilisateur
            $this->addFlash('success', 'Le concert a bien été modifié.');

            return $this->redirectToRoute('shows_index');
        }

        return $this->render('shows/edit.html.twig', [
            'show' => $show,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/shows/{id}", name="shows_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Shows $show, Filesystem $filesystem): Response
    {
        if ($this->isCsrfTokenValid('delete'.$show->getId(), $request->request->get('_token'))) {
            //Stockage de l'ancien nom de fichier image
            $oldImage = $show->getImage();

            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->remove($show);
            $entityManager->flush();

            //Suppression de la miniature associée à la langue de publication
            $oldImage = '../public/media/cache/miniatures/images/'.$oldImage;
            //Si le fichier existe
            if ($filesystem->exists($oldImage)) {
                //Alors on le supprime
                $filesystem->remove($oldImage);
            }
            //Envoi d'un message utilisateur
            $this->addFlash('success', 'Le concert a bien été supprimé.');
        }

        return $this->redirectToRoute('shows_index');
    }

    /**
     * @Route("/admin/api/shows", name="give_shows", methods={"GET"})
     */
    public function giveShows(Request $request, ShowsRepository $showsRepository): JsonResponse
    {
        if ($request->isXmlHttpRequest()) {
            $token = $request->headers->get('authorization');
            if (!$this->isCsrfTokenValid('links', $token)) {
                return new JsonResponse('Unauthorized', 401);
            }
            $shows = $showsRepository->getShows();

            return new JsonResponse($shows, 200);
        }

        return new JsonResponse('Méthode non-autorisée', 405);
    }
}

templates/shows/_delete_form.html.twig
<!-- Button trigger modal -->
<button class="btn btn-danger" data-toggle="modal" data-target="#deleteShow{{ show.id }}ModalCenter">
  <i class="fas fa-trash"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="deleteShow{{ show.id }}ModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteShow{{ show.id }}ModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteShow{{ show.id }}ModalLongTitle">Suppression du concert <span class="font-italic">{{ show.title }}</span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                La suppression du concert <span class="font-italic">{{ show.title }}</span> sera irréversible.
                Voulez-vous vraiment supprimer cet item ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                <form method="post" action="{{ path('shows_delete', {'id': show.id}) }}">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ show.id) }}">
                    <button class="btn btn-danger">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/shows/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/shows/edit.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Editer concert{% endblock %}

{% block body %}
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Editer concert</h1>
				</div>
				<!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item">
							<a href="{{ path('admin') }}">Dashboard</a>
						</li>
						<li class="breadcrumb-item active">Concerts</li>
					</ol>
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<div class="content">
		<div class="container-fluid">

            {{ include('shows/_form.html.twig', {'button_label': 'Modifier'}) }}

            <a href="{{ path('shows_index') }}">back to list</a>

            {{ include('shows/_delete_form.html.twig') }}

    	</div>
	</div>
{% endblock %}
{% block javascripts %}
	{{ encore_entry_script_tags('adminShows') }}
{% endblock %}

templates/shows/index.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Index des concerts{% endblock %}

{% block body %}
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Index des concerts</h1>
				</div>
				<!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item">
							<a href="{{ path('admin') }}">Dashboard</a>
						</li>
						<li class="breadcrumb-item active">Concerts</li>
					</ol>
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<div class="content">
		<div class="container-fluid">

			{% for message in app.flashes('success') %}
				<div class="alert alert-success" role="alert">{{ message }}</div>
			{% endfor %}

			{% for message in app.flashes('fail') %}
				<div class="alert alert-warning" role="alert">{{ message }}</div>
			{% endfor %}

            <a href="{{ path('shows_new') }}" class="btn btn-success my-5">Create new</a>

            <table class="table">
                <thead>
                    <tr>
                        <th>
                        {{ knp_pagination_sortable(shows, 'Titre', 'title') }}
                        </th>
                        <th>
                        {{ knp_pagination_sortable(shows, 'Lieu', 'location') }}
                        </th>
                        <th>
                        {{ knp_pagination_sortable(shows, 'Quand', 'expected_at') }}
                        </th>
                        <th>
                        {{ knp_pagination_sortable(shows, 'Modifié le', 'updated_at') }}
                        </th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for show in shows %}
                    <tr>
                        <td>{{ show.title }}</td>
                        <td>{{ show.location }}</td>
                        <td>{{ show.expectedAt ? show.expectedAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ show.updatedAt ? show.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <a href="{{ path('shows_show', {'id': show.id}) }}">show</a>
                            <a href="{{ path('shows_edit', {'id': show.id}) }}">edit</a>
                            {{ include('shows/_delete_form.html.twig') }}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="6">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
				<div>
					{{ knp_pagination_render(shows) }}
				</div>
			</table>
			<div>
				{{ knp_pagination_render(shows) }}
			</div>

            <a href="{{ path('shows_new') }}" class="btn btn-success my-5">Create new</a>

		</div>
	</div>
{% endblock %}

templates/shows/new.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Nouveau concert{% endblock %}

{% block body %}
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Nouveau concert</h1>
				</div>
				<!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item">
							<a href="{{ path('admin') }}">Dashboard</a>
						</li>
						<li class="breadcrumb-item active">Concerts</li>
					</ol>
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<div class="content">
		<div class="container-fluid">

            {{ include('shows/_form.html.twig') }}

            <a href="{{ path('shows_index') }}" class="btn btn-primary">back to list</a>
    	</div>
	</div>
{% endblock %}
{% block javascripts %}
	{{ encore_entry_script_tags('adminShows') }}
{% endblock %}

templates/shows/show.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Concert <span class="font-italic">"{{ show.title }}"</span>{% endblock %}

{% block body %}
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Concert <span class="font-italic">"{{ show.title }}"</span></h1>
				</div>
				<!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item">
							<a href="{{ path('admin') }}">Dashboard</a>
						</li>
						<li class="breadcrumb-item active">Concerts</li>
					</ol>
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<div class="content">
		<div class="container-fluid">

            <table class="table">
                <tbody>
                    <tr>
                        <th>Title</th>
                        <td>{{ show.title }}</td>
                    </tr>
                    <tr>
                        <th>Location</th>
                        <td>{{ show.location }}</td>
                    </tr>
                    <tr>
                        <th>MetaDescription</th>
                        <td>{{ show.metaDescription }}</td>
                    </tr>
                    <tr>
                        <th>MetaTitle</th>
                        <td>{{ show.metaTitle }}</td>
                    </tr>
                    <tr>
                        <th>Expected_at</th>
                        <td>{{ show.expectedAt ? show.expectedAt|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Image</th>
                        <td>
                        	<img src="{{ asset('images/'~ show.image ) | imagine_filter('min300') }}" alt="Image associé au concert {{ show.title }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Updated_at</th>
                        <td>{{ show.updatedAt ? show.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ show.description|raw }}</td>
                    </tr>
                    <tr>
						<th>Mots-clés en méta donnée</th>
						<td>
							{% for metaKeyword in show.metaKeywords %}
								#{{ metaKeyword }}
							{% else %}
								Pas de mot-clés pour ce concert
							{% endfor %}
						</td>
                    </tr>
                    <tr>
						<th>Mots-clés</th>
						<td>
							{% for keyWord in show.keywords %}
								#{{ keyWord }}
							{% else %}
								Pas de mot-clés pour ce concert
							{% endfor %}
						</td>
                    </tr>
                    <tr>
                        <th>Is_past</th>
                        <td>A developper</td>
                    </tr>
                    <tr>
						<th>Slug</th>
						<td>{{ show.slug }}</td>
					</tr>
                </tbody>
            </table>

            <a href="{{ path('shows_index') }}">back to list</a>

            <a href="{{ path('shows_edit', {'id': show.id}) }}">edit</a>

            {{ include('shows/_delete_form.html.twig') }}
{% endblock %}