src/Entity/Links.php
<?php

namespace App\Entity;

use App\Repository\LinksRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=LinksRepository::class)
 * @Vich\Uploadable
 */
class Links
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $hyperlink;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $position;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *
     * @var int
     */
    private $position_order;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $alt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface
     */
    private $updated_at;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="images", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     *
     * @var bool
     */
    private $is_active;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     *
     * @var bool
     */
    private $is_video;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTimeInterface
     */
    private $uploaded_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getHyperlink(): ?string
    {
        return $this->hyperlink;
    }

    public function setHyperlink(string $hyperlink): self
    {
        $this->hyperlink = $hyperlink;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getPositionOrder(): ?int
    {
        return $this->position_order;
    }

    public function setPositionOrder(int $position_order): self
    {
        $this->position_order = $position_order;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if (null !== $imageFile) {
            $this->updated_at = new \DateTimeImmutable();
        }
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getIsVideo(): ?bool
    {
        return $this->is_video;
    }

    public function setIsVideo(?bool $is_video): self
    {
        $this->is_video = $is_video;

        return $this;
    }

    public function getUploadedAt(): ?\DateTimeInterface
    {
        return $this->uploaded_at;
    }

    public function setUploadedAt(?\DateTimeInterface $uploaded_at): self
    {
        $this->uploaded_at = $uploaded_at;

        return $this;
    }
}

templates/base-admin.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {# <link rel="shortcut icon" href="{{ asset('images/logo_neutre.jpg') }}" type="image/x-icon"> #}
        <title>{% block title %}Tunkal Admin{% endblock %}</title>
        
        <!-- Font Awesome Icons -->
        <link rel="stylesheet" href="{{ asset('adminlte/plugins/fontawesome-free/css/all.min.css') }}">
        <!-- Theme style -->
        <link rel="stylesheet" href="{{ asset('adminlte/dist/css/adminlte.min.css') }}">
        {% block stylesheets %}{% endblock %}
    </head>
    <body class="hold-transition sidebar-mini">

        <div class="wrapper">
            <!-- Navbar -->
            <nav class="main-header navbar navbar-expand navbar-white navbar-light">
                <!-- Left navbar links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#" role="button" title="Rabattre/déployer la barre de navigation"><i class="fas fa-bars"></i></a>
                    </li>
                </ul>

                <!-- Right navbar links -->
                <ul class="navbar-nav ml-auto">
                    <!-- Notifications Dropdown Menu -->
                    <li class="nav-item dropdown">
                        <a class="nav-link" data-toggle="dropdown" title="Accueil et déconnexion" href="#">
                            <i class="fas fa-user fa-fw"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                            <div class="dropdown-divider"></div>
                            <a href="{{ path('home') }}" class="dropdown-item" title="Aller à l'accueil du site">
                                <i class="nav-icon fas fa-home"></i>Accueil du site
                            </a>
                            <div class="dropdown-divider"></div>
                            <a href="{{ path('app_logout') }}" class="dropdown-item" title="Se déconnecter de l'administration du site">
                                <i class="nav-icon fas fa-sign-out-alt"></i>Déconnexion
                            </a>
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- /.navbar -->

            <!-- Main Sidebar Container -->
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <!-- Brand Logo -->
                <a href="{{ path('admin') }}" title="Retour vers la page d'accueil administration">
                    ADMIN
                </a>

                <!-- Sidebar -->
                <div class="sidebar">
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        {# {% if app.user %}
                            <div class="text-light">
                                Bienvenue {{ app.user.firstname }} !
                            </div>
                        {% endif %} #}
                    </div>

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            {# Comptes utilisateurs #}
                            <li class="nav-item has-treeview">
                                <a title="Les utilisateurs de l'administration du site" href="#" class="nav-link">
                                <i class="nav-icon fas fa-user-cog"></i>
                                <p>
                                    Utilisateurs
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a title="Liste de utilisateurs" href="{{ path('users_index') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Liste des utilisateurs</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a title="Nouvel utilisateur" href="{{ path('users_new') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Nouvel utilisateur</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>                            

                            {# Avis des visiteurs #}
                            <li class="nav-item has-treeview">
                                <a href="{{ path('comments_index') }}" class="nav-link">
                                    <i class="nav-icon far fa-comments"></i>
                                    <p>
                                        Avis visiteurs
                                    </p>
                                </a>
                            </li>

                            {# Concerts #}
                            <li class="nav-item has-treeview">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-table"></i>
                                    <p>
                                        Concerts
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="{{ path('shows_index') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Liste</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ path('shows_new') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Nouveau</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            {# Gestion des articles #}
                            <li class="nav-item has-treeview">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-book"></i>
                                    <p>
                                        Articles
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="{{ path('posts_index') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Liste</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ path('posts_new') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Nouveau</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            {# Gestion des liens #}
                            <li class="nav-item has-treeview">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-link"></i>
                                    <p>
                                        Gestion des liens
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="{{ path('links_index') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Liste</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ path('links_new') }}" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Nouveau</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
                <!-- /.sidebar -->
            </aside>
        
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                {% block body %}{% endblock %}
            </div>
            <!-- /.content-wrapper -->

            <!-- Main Footer -->
            <footer class="main-footer">
                <!-- To the right -->
                <div class="float-right d-none d-sm-inline">
                Anything you want
                </div>
                <!-- Default to the left -->
                <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
            </footer>
        </div>
        <!-- ./wrapper -->


        <!-- REQUIRED SCRIPTS -->
        <!-- jQuery -->
        <script src="{{ asset('adminlte/plugins/jquery/jquery.min.js')}}"></script>
        <!-- Bootstrap 4 -->
        <script src="{{ asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
        <!-- AdminLTE App -->
        <script src="{{ asset('adminlte/dist/js/adminlte.min.js') }}"></script>
		{% block javascripts %}
		{% endblock %}
    </body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Tunkal">
        <meta name="copyright" content="Copyright © 2019-{{ 'now' | date('Y') }} Tunkal. All rights reserved.">

       	{# Instagram #}
        <meta property="og:site_name" content="Tunkal">
        <meta property="og:image" content="{{ asset('images/logo.webp')|imagine_filter('min300') }}">
	    <meta property="og:image:width" content="300">
	    {# <meta property="og:image:height" content="300"> #}
        {# Fin Instagram #}

        {% block head %}{% endblock %}

		<link rel="shortcut icon" href="{{ asset('images/ptiLogo2.webp') }}" type="image/x-icon">
		<title>
			{% block title %}Guitariste de Thrash Death Metal Bourgogne Mâcon - Tunkal
			{% endblock %}
		</title>

		<!-- Font Awesome Icons -->
        <link rel="stylesheet" href="{{ asset('adminlte/plugins/fontawesome-free/css/all.min.css') }}">

		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}
	</head>
	<body>
		<header>
			<a href="{{ path('home') }}" title="Aller à l'accueil">
				<img class="logoheader" src="{{ asset('images/logo.webp')|imagine_filter('min500') }}" alt="Logo de tunkal" data-desktop-image="{{ asset('images/logo.webp') }}" data-mobile-image="{{ asset('images/logo.webp')|imagine_filter('min500') }}">
			</a>
			<h1>Tunkal Music</h1>

			{% if links()|filter( link => link.position == 'header' )|length > 0 %}
				<div class='socNetWork'>
					{# Boucle sur liens header #}
					{% for link in links()|filter( link => link.position == 'header' )|sort((a, b) => a.positionOrder <=> b.positionOrder) %}
						<a href="{{ link.hyperlink }}" title="{{ link.title }}" 
						target="{{ (link.type == "external") ? '_blank' : '_self' }}" >{{ link.content|raw }}</a>
					{% endfor %}
					{# Fin Boucle sur liens header #}
				</div>
			{% endif %}
			{% if links()|filter( link => link.position == 'nav' )|length > 0 %}
				<nav>

				    <!-- Hamburger -->
					<span id="navMenu" title="Menu">
						<i class="fas fa-bars"></i>
					</span>
					<!-- Fin hamburger -->

					<!-- Barre navigation vue ordi -->
					<div class="menuPrincipal">
						<a href="{{ path('home') }}" title="Aller à l'accueil" 
							target="_self" >Home</a>
						{# Boucle sur liens nav #}
						{% for link in links()|filter( link => link.position == 'nav' )|sort((a, b) => a.positionOrder <=> b.positionOrder) %}	
						<a href="{{ link.hyperlink }}" title="{{ link.title }}" 
							target="{{ (link.type == "external") ? '_blank' : '_self' }}" >{{ link.content }}</a>
						{% endfor %}
						{# Fin Boucle sur liens header #}
					</div>
				</nav>			
			{% endif %}

		</header>

        <span id="scroll" title="Back to home">
	        <i class="fas fa-chevron-circle-up"></i>
        </span>

		<main>
			{% block body %}{% endblock %}		
		</main>
		<footer>
			<p>&copy; {{ 'now' | date('Y') }} Tunkal</p>
		</footer>

		{{ encore_entry_script_tags('app') }}
		{% block javascripts %}
		{% endblock %}
	</body>
</html>