src/Entity/Comments.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentsRepository::class)
 */
class Comments
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $pseudo;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $is_moderated;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTimeInterface
     */
    private $sent_at;

    /**
     * @ORM\ManyToOne(targetEntity=Posts::class, inversedBy="comments")
     *
     * @var Posts
     */
    private $post;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIsModerated(): ?bool
    {
        return $this->is_moderated;
    }

    public function setIsModerated(bool $is_moderated): self
    {
        $this->is_moderated = $is_moderated;

        return $this;
    }

    public function getSentAt(): ?\DateTimeInterface
    {
        return $this->sent_at;
    }

    public function setSentAt(\DateTimeInterface $sent_at): self
    {
        $this->sent_at = $sent_at;

        return $this;
    }

    public function getPost(): ?Posts
    {
        return $this->post;
    }

    public function setPost(?Posts $post): self
    {
        $this->post = $post;

        return $this;
    }
}

src/Form/CommentsType.php
<?php

namespace App\Form;

use App\Entity\Comments;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Blank;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

class CommentsType extends AbstractType
{
    /**
     *
     * @param FormBuilderInterface $builder
     * @param array<string, mixed> $options
     * @return void
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('pseudo', TextType::class, [
            'required' => true,
            'label' => 'Votre pseudo',
            'attr' => [
                'minlength' => 4,
                'maxlength' => 20,
                'pattern' => '[A-Za-z]{4,20}.{0,}',
                'title' => 'Votre pseudo doit comporter entre 4 et 20 carctères et commencer par 4 lettres minimum',
            ],
            'constraints' => [
                new NotBlank([
                    'message' => 'Nom/pseudo requis',
                ]),
                new Length([
                    'min' => 4,
                    'max' => 20,
                    'minMessage' => 'Votre pseudo doit comporter au moins {{ limit }}
                    caractères.',
                    'maxMessage' => 'Votre pseudo doit comporter moins de {{ limit }}
                    caractères.',
                ]),
                new Regex([
                    'pattern' => '/^[a-zA-Z]{4,20}/',
                    'match' => true,
                    'message' => 'Votre pseudo doit commencer par 4 lettres au moins',
                ]),
            ],
        ])
        ->add('content', TextareaType::class, [
            'required' => true,
            'label' => 'Votre commentaire',
            'attr' => [
                'minlength' => 2,
                'maxlength' => 240,
                'pattern' => '[A-Za-z]{2,240}.{0,}',
                'title' => 'Votre commentaire doit comporter entre 2 et 240 carctères et commencer par 2 lettres minimum',
            ],
            'constraints' => [
                new NotBlank([
                    'message' => 'Commentaire requis',
                ]),
                new Length([
                    'min' => 2,
                    'max' => 240,
                    'minMessage' => 'Votre commentaire doit comporter au moins {{ limit }}
                    caractères.',
                    'maxMessage' => 'Votre commentaire doit comporter moins de {{ limit }}
                    caractères.',
                ]),
                new Regex([
                    'pattern' => '/^[a-zA-Z]{2,240}/',
                    'match' => true,
                    'message' => 'Votre commentaire doit commencer par 2 lettres au moins',
                ]),
            ],
        ])
        ->add('nosiar', HiddenType::class, [
            'required' => true,
            'mapped' => false,
            'constraints' => [
                new Blank([
                    'message' => 'Le champ doit rester vide.',
                ]),
            ],
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comments::class,
        ]);
    }
}

src/Controller/CommentsController.php
<?php

namespace App\Controller;

use App\Entity\Comments;
use App\Form\CommentsType;
use App\Repository\CommentsRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/comments")
 */
class CommentsController extends AbstractController
{
    /**
     * @Route("/", name="comments_index", methods={"GET"})
     */
    public function index(CommentsRepository $commentsRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $comments = $paginator->paginate(
            $commentsRepository->findAll(),
            //Le numero de la page, si aucun numero, on force la page 1
            $request->query->getInt('page', 1),
            //Nombre d'élément par page
            10
        );

        return $this->render('comments/index.html.twig', [
            'comments' => $comments,
        ]);
    }

    /**
     * @Route("/{id}", name="comments_show", methods={"GET"})
     */
    public function show(Comments $comment): Response
    {
        return $this->render('comments/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="comments_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Comments $comment): Response
    {
        $form = $this->createForm(CommentsType::class, $comment);
        $form->remove('pseudo');
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setIsModerated(true);
            $this->getDoctrine()->getManager()->flush();
            //Envoi d'un message utilisateur
            $this->addFlash('success', 'L\'avis client a bien été modifié.');

            return $this->redirectToRoute('comments_index');
        }

        return $this->render('comments/edit.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="comments_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Comments $comment): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($comment);
            $entityManager->flush();
            //Envoi d'un message utilisateur
            $this->addFlash('success', 'Le commentaire a bien été supprimé');
        }

        return $this->redirectToRoute('comments_index');
    }
}

templates/comments/_delete_collection.html.twig
<!-- Button trigger modal -->
<button id="trash" type="button" class="btn btn-danger d-none" data-toggle="modal" data-target="#deleteCollectionModalCenter">
   <i class="fas fa-trash"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="deleteCollectionModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteCollectionModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteCollectionModalLongTitle">Suppression de tous ces commentaires ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                <button id="confirm_delete" class="btn btn-danger" data-dismiss="modal">Supprimer ces commentaires</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/comments/_delete_form.html.twig
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteComment{{ comment.id }}ModalCenter">
   <i class="fas fa-trash"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="deleteComment{{ comment.id }}ModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteComment{{ comment.id }}ModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteComment{{ comment.id }}ModalLongTitle">Suppression du commentaire de <span class="font-italic">"{{ comment.pseudo }}"</span> du <span class="font-italic">{{ comment.sentAt|date('d-m-Y H:i:s') }}</span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                La suppression du commentaire de <span class="font-italic">"{{ comment.pseudo }}"</span> du <span class="font-italic">{{ comment.sentAt|date('d-m-Y H:i:s') }}</span> sera irréversible.
                Voulez-vous vraiment supprimer ce commentaire ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                <form method="post" action="{{ path('comments_delete', {'id': comment.id}) }}">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
                    <button class="btn btn-danger">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/comments/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

templates/comments/edit.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Ludo et Sophie - Modérer avis clients
{% endblock %}

{% block body %}
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Modérer avis client de {{ comment.pseudo }} le {{ comment.sentAt|date('d-m-Y H:i:s') }}</h1>
				</div>
				<!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item">
							<a href="{{ path('admin') }}">Dashboard</a>
						</li>
						<li class="breadcrumb-item active">Avis clients</li>
					</ol>
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<div class="content">
		<div class="container-fluid">

			{{ include('comments/_form.html.twig', {'button_label': 'Modérer'}) }}

			<a href="{{ path('comments_index') }}" class="btn btn-primary" >Retour à la liste</a>

			{{ include('comments/_delete_form.html.twig') }}
		</div>
	</div>
{% endblock %}

templates/comments/index.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Index des Commentaires
{% endblock %}

{% block body %}
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Index des Commentaires</h1>
				</div>
				<!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item">
							<a href="{{ path('admin') }}">Dashboard</a>
						</li>
						<li class="breadcrumb-item active">Commentaires</li>
					</ol>
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<div class="content">
		<div class="container-fluid">

			<div id="message-api" class="alert d-none" role="alert"></div>

			{% for message in app.flashes('success') %}
				<div class="alert alert-success" role="alert">{{ message }}</div>
			{% endfor %}

			{% for message in app.flashes('fail') %}
				<div class="alert alert-warning" role="alert">{{ message }}</div>
			{% endfor %}

			{# Barre de recherche #}
			{# <div class="search_filter mb-5"> 
				<form class="search_bar" action="{{ path('comments_index') }}" method="get">
					<div class="row">
						<input class="col-5 p-2" type="text" name="search" placeholder="Rechercher parmis les pseudos des auteurs et leurs contenus">
						
						<select name="isModaratedFilter" id="isModaratedFilter">
							<option value="">Commentaires modérés</option>
							<option value="true">Oui</option> 
							<option value="false">Non</option> 
						</select>
						
						<button type="submit" class="btn btn-primary" class=" button violetBackground">OK</button>		
						<a class="btn btn-secondary mx-1" href="{{ path('comments_index') }}" title="Retour à la liste des produits">Reset</a>	
					</div>
				</form>
			</div> #}
			{# Fin barre de recherche #}

			<table class="table">
				<thead>
					<tr>
						<th>
							{{ include('comments/_delete_collection.html.twig') }}
						</th>
						<th>
							{{ knp_pagination_sortable(comments, 'Ecrit par', 'pseudo') }}
						</th>
						<th class="d-none d-lg-table-cell">
							{{ knp_pagination_sortable(comments, 'Contenu', 'content') }}
						</th>
						<th class="d-none d-sm-table-cell">
							{{ knp_pagination_sortable(comments, 'Concernant l\'article', 'post.title') }}
						</th>
						<th>
							{{ knp_pagination_sortable(comments, 'Date', 'sent_at') }}
						</th>
						<th class="d-none d-sm-table-cell">
							{{ knp_pagination_sortable(comments, 'Commentaire modéré', 'isModerated') }}
						</th>
						<th>actions</th>
					</tr>
				</thead>
				<tbody>
					{% for comment in comments %}
						<tr>
							<td>
								<input type="checkbox" id={{ "comment_"~comment.id }} name={{ "delete_comment_"~comment.id }} data-commentid={{ comment.id }}>
								<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
							</td>							
							<td>{{ comment.pseudo }}</td>
							<td class="d-none d-lg-table-cell">
								<a href="{{ path('comments_show', {'id': comment.id}) }}" >
									{{ comment.content }}
								</a>
							</td>
							<td class="d-none d-sm-table-cell">
								{% if comment.post != null %}
									<a title="Voir la article associée" href="{{ path('posts_show', {id:comment.post.id}) }}">{{ comment.post.title }}</a>
								{% else %}
									Commentaire associé à aucun article
								{% endif %}
							</td>
							<td>{{ comment.sentAt|date('d-m-Y H:i:s') }}</td>
							<td class="d-none d-sm-table-cell">
								{{ (comment.isModerated)?'Oui':'Non' }}
							</td>
							<td>
								<a href="{{ path('comments_show', {'id': comment.id}) }}" class="btn btn-primary" ><i class="fas fa-glasses"></i></a>
								<a href="{{ path('comments_edit', {'id': comment.id}) }}" class="btn btn-warning">Modérer</a>
								{{ include('comments/_delete_form.html.twig') }}
							</td>

						</tr>
					{% else %}
						<tr>
							<td colspan="4">Aucun commentaire</td>
						</tr>
					{% endfor %}
				</tbody>
				<div>
					{{ knp_pagination_render(comments) }}
				</div>
			</table>
			<div>
				{{ knp_pagination_render(comments) }}
			</div>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	{{ encore_entry_script_tags('adminDeleteComments') }}
{% endblock %}

templates/comments/show.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %}Commentaire
	{{ comment.pseudo }}
	le
	{{ comment.sentAt|date('d-m-Y H:i:s') }}
{% endblock %}

{% block body %}
	<!-- Content Header (Page header) -->
	<div class="content-header">
		<div class="container-fluid">
			<div class="row mb-2">
				<div class="col-sm-6">
					<h1 class="m-0 text-dark">Commentaire {{ comment.pseudo }} le {{ comment.sentAt|date('d-m-Y H:i:s') }}</h1>
				</div>
				<!-- /.col -->
				<div class="col-sm-6">
					<ol class="breadcrumb float-sm-right">
						<li class="breadcrumb-item">
							<a href="{{ path('admin') }}">Dashboard</a>
						</li>
						<li class="breadcrumb-item active">Avis clients</li>
					</ol>
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div>
		<!-- /.container-fluid -->
	</div>
	<!-- /.content-header -->

	<!-- Main content -->
	<div class="content">
		<div class="container-fluid">

			<table class="table">
				<tbody>
					<tr>
						<th>Pseudo</th>
						<td>{{ comment.pseudo }}</td>
					</tr>
					<tr>
						<th>Ecrit le</th>
						<td>{{ comment.sentAt|date('d-m-Y H:i:s') }}</td>
					</tr>
					<tr>
						<th>Concernant l'article</th>
						<td>
							{% if comment.post != null %}
								<a title="Voir l'article associée" href="{{ path('posts_show', {id:comment.post.id}) }}">{{ comment.post.title }}</a>
							{% else %}
								Commentaire associé à aucun article
							{% endif %}
						</td>
					</tr>
					<tr>
						<th>Contenu</th>
						<td>{{ comment.content }}</td>
					</tr>
				</tbody>
			</table>

			<a href="{{ path('comments_index') }}" class="btn btn-primary" >Retour à la liste</a>

			<a href="{{ path('comments_edit', {'id': comment.id}) }}" class="btn btn-warning">Modérer</a>

			{{ include('comments/_delete_form.html.twig') }}
		</div>
	</div>
{% endblock %}